name: CriticalLife
main: me.TheFr0gsL3gs.critical_life.Main
version: 1.0
api-version: 1.21.4
author: TheFr0gsL3gs
commands:
  event:
    description: Trigger event
    usage: /<command> <event>
    permission: op
  set-lives:
    description: Manually set amount of lives for a player
    usage: /<command> <player> <lives>
    permission: op
  swap-lives:
    description: Swap the lives of two players
    usage: /<command> <player 1> <player 2>
    permission: op
  gift-life:
    description: Gift a life to someone
    usage: /<command> <player>
  lives:
    description: See how many lives you have left
    usage: /<command>
  submit:
    description: Submit a bounty
    usage: /<command>
  take-life:
    description: Take a life away from someone
    usage: /<command> <player>
